class StringUtils {
  static const signIn = "Sign In";
  static const signInEmail = "Enter Email Address";
  static const signInPassword = "Enter Password";
  static const forgotPassword = "Forgot Password?";
  static const rememberPassword = "Remember Me";
  static const login = "Login";
  static const forgotScreenDetail = "Enter your email to reset your password";
  static const sendLink = "Send Link";
  static const cancel = "Cancel";
  static const introOneTitle = "Book an Appointment";
  static const introOneSubTitle = "Lorem Ipsum is simply dummy text of the printing and typesetting industry";
  static const introTwoTitle = "Schedule Live Consultation";
  static const introTwoSubTitle = "Lorem Ipsum is simply dummy text of the printing and typesetting industry";
  static const introThreeTitle = "Read Prescriptions";
  static const introThreeSubTitle = "Lorem Ipsum is simply dummy text of the printing and typesetting industry";
  static const appointment = "Appointment";
  static const bills = "Bills";
  static const diagnosisTests = "Diagnosis Tests";
  static const documents = "Documents";
  static const noticeBoards = "Notice Boards";
  static const invoices = "Invoices";
  static const liveConsultations = "Live Consultations";
  static const patientsCases = "Patients Cases";
  static const patientAdmissions = "Patient Admissions";
  static const prescriptions = "Prescriptions";
  static const vaccinatedPatients = "Vaccinated Patients";
  static const logOut = "Logout";
}
